# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8602babce779ea9afc9d8e184cbfe37429439c8f83f30a0e33e8aabcbacc294d87808d5d3756e39e4a3d72ed94a3717a570d4b568be445991b6d4cdd935281f6

test:
  secret_key_base: 6d4e1a057fc16e1a16790083a51c188bb8ff532965d64e7c22cd50421e36ecb4b8524f89f7b4f632c9bac644eaeb45f99d9b72660f162e509d6833a110d466b7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
